#!/usr/bin/env python3
"""Run a benchmark's own no-data probe while controlling the option geometry.

A "zero-shot" or "no-data" baseline gives a solver the question and the answer
options but withholds the data it would need, and the field reads an
above-chance score as evidence that the answer leaked into pretraining. That
reading has a competing explanation. If distractors are generated by perturbing
the true value, the key lands in the interior of the sorted options, and a
solver with any preference for middling numbers scores above chance while
knowing nothing.

This script separates the two by re-running the probe under five conditions
that differ only in the option values:

  original           the released options
  placebo            distractor values redrawn, the key's sorted rank held
  repaired           distractor values redrawn, the key's sorted rank uniform
  original_stemless  released options, question text withheld
  repaired_stemless  repaired options, question text withheld

``placebo`` is the control that matters: it perturbs the distractors as much as
``repaired`` does but leaves the leaking geometry in place. If accuracy tracks
``original`` under the placebo and falls under the repair, the margin is carried
by rank, not by the values and not by recall.

Scoring is deterministic. The prompt is BixBench's own MCQ template, the
assistant turn is pre-filled with the ``<answer>`` tag their template asks for,
and the answer is the arg-max over the four letter logits at that position. No
sampling, so a rerun on the same hardware reproduces bit for bit.

``--repair-mode`` chooses which repair the repaired arms apply: ``rank`` (the
sorted value only), ``two-channel``, ``multi`` (every audited ordering, which is
the shipped repair), ``exchangeable`` (``exchangeable_repair.py``, which makes
the key a uniform draw from its own option set instead of uniformising any one
ordering), or ``multi-tie``, which adds written length under the
opposite tie-break -- the coordinate the surface rule family actually reads and
the shipped repair does not target. Running the same models under ``multi`` and
``multi-tie`` is how the paper asks whether closing a coordinate a model was not
using changes what it answers.

Only this script needs a GPU and ``torch``/``transformers``. It writes raw
per-item outcomes to ``results/probe_raw/``; ``probe_analysis.py`` turns those
into the reported statistics using the standard library alone.
"""
import argparse
import gzip
import hashlib
import io
import json
import random
import time
from pathlib import Path

from mcq_audit import (LENGTH_LATER, SURFACE_ORDERINGS, _draw_rank, build_items,
                       construct_row, fit_pair_weights, fit_target_weights,
                       placeable_value_ranks, placebo_row, rank_of, repair_row,
                       repair_row_multi, repair_row_two_channel)
from option_artifacts import N_OPTIONS

ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
LETTERS = ALPHABET[:N_OPTIONS]          # the four-option default


def letters_for(k):
    if k > len(ALPHABET):
        raise ValueError(f"{k} options exceeds the alphabet")
    return ALPHABET[:k]


def open_outcomes(path, mode="rt"):
    """Open a per-decision outcome file, gzipped or not.

    Outcomes are written gzipped: they are the thing that lets every reported
    statistic be re-derived without a GPU, so they are committed, and at a
    tenth of the size that is a reasonable thing to commit. Readers accept
    either form so an uncompressed file dropped in still works.
    """
    path = Path(path)
    if path.suffix == ".gz":
        return io.TextIOWrapper(gzip.open(path, mode.replace("t", "b")), encoding="utf-8")
    return path.open(mode, encoding="utf-8")


def outcome_files(directory):
    """Every outcome file in a directory, compressed or plain, deduplicated."""
    directory = Path(directory)
    seen, paths = set(), []
    for path in sorted(directory.glob("*.jsonl*")):
        stem = path.name[:-3] if path.name.endswith(".gz") else path.name
        if stem not in seen:
            seen.add(stem)
            paths.append(path)
    return paths
WITHHELD = "[withheld]"

# Verbatim from BixBench bixbench/prompts.py (MCQ_PROMPT_TEMPLATE_WITHOUT_REFUSAL)
# at commit 4931118. The missing newline before "IMPORTANT" is theirs; keeping it
# makes this a replication rather than a re-specification.
MCQ_PROMPT_TEMPLATE = (
    "Extract the single letter answer to the following question from the given options."
    " You must pick one answer even if you are unsure."
    "\n\nQuestion: {question}"
    "\n\nOptions:\n{options}"
    "IMPORTANT: You must only output a single letter answer in XML format."
    "\n\n Example Output: <answer> X </answer>"
)
# The template's example output is "<answer> X </answer>", so the letter the
# model writes is space-prefixed. We stop the prefix before that space and score
# the " A".." D" tokens, which is where these tokenizers put the probability
# mass; ending the prefix with the space instead splits it into its own token
# and leaves the model predicting a second space.
ANSWER_PREFIX = "<answer>"
LETTER_VARIANTS = [" {}", "{}"]

ARMS = ("original", "placebo", "repaired", "original_stemless", "repaired_stemless")
# Constructible but not run by default. ``placebo_stemless`` is the control for
# a stem-withheld comparison the way ``placebo`` is for a stem-shown one: it
# carries redrawn distractor values with the key's rank held, so a gain that
# survives it is not geometry but the redrawn options being easier to dismiss.
# Left out of the default five because every arm costs a full forward pass over
# the file, and added by name when a claim needs it.
EXTRA_ARMS = ("placebo_stemless",)


# --------------------------------------------------------------------------
def option_block(options, permutation, letters=LETTERS):
    """Render options as BixBench does: ``(A) value`` per line, no trailing newline."""
    return "\n".join(f"({letters[slot]}) {options[src]}"
                     for slot, src in enumerate(permutation))


def two_channel_row(options, rng, weights=None, search="sample"):
    """The repair that uniformises the key's rank under value *and* isolation."""
    target = None if weights is None else _draw_rank(
        rng, len(options), weights.get("lexical isolation"))
    result = repair_row_two_channel(options, rng, isolation_target=target,
                                    **_search_options(search))
    return result[0] if result else None


def multi_channel_row(options, rng, weights=None, search="sample", with_tie=False):
    """The repair that uniformises the key's rank under every audited ordering.

    ``with_tie`` adds a fifth coordinate the audit does not report: written
    length under the opposite tie-break, which is the one the surface rule
    family actually reads. The three-coordinate repair *opens* it on MMLU
    (held_out_orderings.py), so the probe needs to be able to ask what a model
    collects from a file where it was closed too.
    """
    k = len(options)
    if search == "construct":
        # The value rank is drawn from this item's placeable set too, exactly as
        # mcq_audit.apply_repair does it. Drawing it uniformly here and letting
        # the construction fail where it cannot be met would make the probe's
        # repaired arm a different repair from the audited one.
        value_target = None
        value_weights = (weights or {}).get("sorted value")
        if value_weights is not None:
            placeable = sorted(placeable_value_ranks(options, rng, k))
            if placeable:
                mass = [value_weights[rank] for rank in placeable]
                value_target = (rng.choices(placeable, weights=mass, k=1)[0]
                                if sum(mass) else rng.choice(placeable))
        result = construct_row(options, rng, value_target=value_target,
                               pair_weights=weights,
                               orderings=(SURFACE_ORDERINGS + (LENGTH_LATER,)
                                          if with_tie else SURFACE_ORDERINGS))
        return result[0] if result else None
    targets = (None if weights is None
               else {name: _draw_rank(rng, k, weights[name]) for name in weights})
    result = repair_row_multi(options, rng, targets=targets, **_search_options(search))
    return result[0] if result else None


# ``mcq_audit`` owns the definition of each search; re-deriving it here is how
# the probe and the audit come to disagree about what "the repair" is.
from mcq_audit import SEARCHES as REPAIR_SEARCHES  # noqa: E402
from mcq_audit import _search_options  # noqa: E402,F401


def _rank_only(options, rng, weights=None, search="sample"):
    """``repair_row``, which takes no surface targets."""
    return repair_row(options, rng)


def multi_tie_row(options, rng, weights=None, search="sample"):
    """``multi_channel_row`` with the reversed-tie length coordinate as well."""
    return multi_channel_row(options, rng, weights, search, with_tie=True)


def exchangeable_row_arm(options, rng, weights=None, search="sample"):
    """Regenerate the whole option set with the key at a uniform slot.

    A different kind of repair from the other three: it uniformises nothing in
    particular and so needs no targets, no calibration and no search. What it
    buys is the class of statistics the rank guarantee does not cover -- the
    learned solver's ``relative magnitude`` above all -- and what it costs is
    the items it cannot rewrite at all, which keep their released options here
    exactly as an unreachable rank target does.
    """
    from exchangeable_repair import exchangeable_row
    result = exchangeable_row(options, rng)
    return result[0] if result else None


REPAIRS = {"rank": _rank_only, "two-channel": two_channel_row,
           "multi": multi_channel_row, "multi-tie": multi_tie_row,
           "exchangeable": exchangeable_row_arm}
# Repair modes whose targets come from a distribution fitted to the whole file
# rather than drawn uniformly per item. Fitting per item would defeat the
# purpose: what is being corrected is a property of the corpus (mcq_audit._tilt).
CALIBRATED = {"two-channel", "multi", "multi-tie"}


def build_conditions(items, draws, seed, k=N_OPTIONS, arms=ARMS, repair="rank",
                     calibrate=False, search="sample"):
    """One record per (item, arm, draw): the prompt text and how to grade it.

    The letter permutation for a given (item, draw) is shared across arms, so an
    item the redraw cannot touch — anything without four distinct numeric
    options — produces a byte-identical prompt in every arm. Those collapse in
    the de-duplication below, which is also a check that the pipeline adds no
    noise of its own to the control items.
    """
    repair_fn = REPAIRS[repair]
    weights = None
    if (calibrate or search == "construct") and repair in CALIBRATED:
        numeric = [item for item in items if item["rank"] is not None]
        orderings = (("lexical isolation",) if repair == "two-channel"
                     else SURFACE_ORDERINGS)
        if search == "construct":
            weights, trace = fit_pair_weights(numeric, k, f"{seed}|calibrate",
                                              with_tie=repair == "multi-tie")
            trace = [] if trace is None else [trace["widest_attainable_rank_share"]]
        else:
            weights, trace = fit_target_weights(numeric, k, f"{seed}|calibrate",
                                                orderings=orderings,
                                                **_search_options(search))
        if trace:
            widest = ", ".join(f"{name} {share:.1%}" for name, share in trace[-1].items())
            print(f"  target distribution fitted on {min(len(numeric), 400)} items; "
                  f"widest realised rank after fitting: {widest} (flat is {1 / k:.1%})")
    records = []
    for draw in range(draws):
        # Seeded from strings, not tuple hashes: PYTHONHASHSEED randomises those.
        # The repair's stream is seeded the same way for either repair mode, so
        # the released and stemless arms are byte-identical across modes and the
        # two modes' repaired arms are directly comparable.
        rep_rng = random.Random(f"{seed}|{draw}|repair")
        pla_rng = random.Random(f"{seed}|{draw}|placebo")
        for item in items:
            variants = {"original": item["options"]}
            applied = {"original": True}
            if item["rank"] is not None:
                # A small-integer key cannot always be placed at the drawn rank:
                # there may be no three distinct same-style values below it. Those
                # items keep their released options and are flagged, so the
                # analysis can separate "the repair a maintainer would ship" from
                # "the repair where it is arithmetically feasible".
                for arm, draw_fn, rng in (("repaired", repair_fn, rep_rng),
                                          ("placebo", placebo_row, pla_rng)):
                    redrawn = (draw_fn(item["options"], rng, weights, search)
                               if arm == "repaired" else draw_fn(item["options"], rng))
                    variants[arm] = redrawn or item["options"]
                    applied[arm] = redrawn is not None
            else:
                variants["repaired"] = variants["placebo"] = item["options"]
                applied["repaired"] = applied["placebo"] = False

            perm_rng = random.Random(f"{seed}|{draw}|{item['question_id']}")
            permutation = list(range(k))
            perm_rng.shuffle(permutation)

            for arm in arms:
                base, stemless = (arm.split("_")[0], arm.endswith("stemless"))
                options = variants[base]
                prompt = MCQ_PROMPT_TEMPLATE.format(
                    question=WITHHELD if stemless else item["question"],
                    options=option_block(options, permutation, letters_for(k)))
                # slot -> sorted-rank of the value shown there, for the choice-bias analysis
                ranks = rank_of_each_slot(options, permutation)
                records.append({
                    "question_id": item["question_id"], "cluster": item["cluster"],
                    "arm": arm, "draw": draw, "prompt": prompt,
                    "target_letter": letters_for(k)[permutation.index(item["key"])],
                    # rank_of, not option_artifacts.numeric_rank: the latter
                    # accepts four options only and would silently record None.
                    "key_rank": rank_of(options, item["key"]),
                    "slot_ranks": ranks, "is_numeric": item["rank"] is not None,
                    "redraw_applied": applied[base], "released_rank": item["rank"],
                    # Carried for model-free solvers, which read the options
                    # directly rather than through a tokeniser.
                    "options_shown": [options[src] for src in permutation],
                    "question_text": WITHHELD if stemless else item["question"],
                })
    return records


def rank_of_each_slot(options, permutation):
    """For each presented slot, the rank of its value among the sorted options."""
    from option_artifacts import parse_number
    values = [parse_number(o) for o in options]
    if any(v is None for v in values) or len(set(values)) < len(values):
        return None
    order = sorted(range(len(values)), key=lambda i: values[i])
    rank = {src: order.index(src) for src in range(len(values))}
    return [rank[src] for src in permutation]


# --------------------------------------------------------------------------
def letter_token_ids(tokenizer, k=N_OPTIONS):
    """First-token id for each answer letter as it follows the prefix.

    Preference order is " A" then "A": the space-prefixed form matches the
    template's own example. Whichever form is used, it must tokenise to a single
    token and the four ids must be distinct, or the read-out would not be
    comparing like with like across options.
    """
    for variant in LETTER_VARIANTS:
        ids = []
        for letter in letters_for(k):
            encoded = tokenizer.encode(variant.format(letter), add_special_tokens=False)
            if len(encoded) != 1:
                ids = None
                break
            ids.append(encoded[0])
        if ids and len(set(ids)) == len(ids):
            return ids, variant
    raise RuntimeError("no single-token, distinct encoding of the answer letters")


def render(tokenizer, prompt):
    """Chat prompt plus the pre-filled ``<answer>`` tag the template asks for."""
    text = tokenizer.apply_chat_template([{"role": "user", "content": prompt}],
                                         tokenize=False, add_generation_prompt=True)
    return text + ANSWER_PREFIX


def _score_chunk(model, tokenizer, texts, ids, device):
    """One forward pass: arg-max letter and the letter probabilities per prompt."""
    import torch

    batch = tokenizer(texts, return_tensors="pt", padding=True,
                      add_special_tokens=False).to(device)
    logits = model(**batch).logits[:, -1, :].float()
    letters = logits[:, ids]
    probs = torch.softmax(letters, dim=-1)
    picks = letters.argmax(dim=-1)
    return [(int(picks[row]), [round(p, 6) for p in probs[row].tolist()])
            for row in range(len(texts))]


def score(model, tokenizer, prompts, ids, batch_size, device, log_every=40, retries=3):
    """Arg-max letter and the letter probabilities, for each prompt.

    Prompts are scored shortest-first so each batch pads to roughly its own
    length. That is not only for speed. In bfloat16 the read-out is sensitive to
    how much padding a batch carries, because padding changes the shape of every
    reduction: the same prompt scored alone and in a batch padded 2 tokens wider
    can move a letter probability by 0.2, and one padded to fifteen times its
    length can change the arg-max. It is a precision effect and not a masking
    bug -- in float32 the same comparison drifts by 3e-5 -- so sorting by length
    keeps it small rather than fixing it. A run is deterministic given its
    settings; changing the set of arms changes the batching, and about 3% of
    decisions differ between two such runs, worth about 0.1 points of pooled
    accuracy against the effects reported here of 3.7 and 9.1 points. A batch that raises is retried in halves after clearing the cache:
    this machine's driver and NVML library disagree, and the allocator can hit
    an NVML assertion tens of thousands of prompts into a run. Halving rather
    than skipping keeps every prompt scored, so a retry changes nothing about
    the numbers -- only about whether they arrive.
    """
    import torch

    order = sorted(range(len(prompts)), key=lambda i: len(prompts[i]))
    out = [None] * len(prompts)
    started = time.time()
    with torch.inference_mode():
        for b, start in enumerate(range(0, len(order), batch_size)):
            chunk = order[start:start + batch_size]
            pending, attempt = [chunk], 0
            while pending:
                piece = pending.pop()
                try:
                    scored = _score_chunk(model, tokenizer, [prompts[i] for i in piece],
                                          ids, device)
                except RuntimeError as error:
                    attempt += 1
                    if attempt > retries or len(piece) == 1:
                        raise
                    print(f"    batch of {len(piece)} failed ({error.__class__.__name__}); "
                          f"retrying in halves", flush=True)
                    torch.cuda.empty_cache()
                    middle = len(piece) // 2
                    pending.extend([piece[:middle], piece[middle:]])
                    continue
                for row, i in enumerate(piece):
                    out[i] = scored[row]
            if b % log_every == 0:
                done = start + len(chunk)
                rate = done / max(time.time() - started, 1e-9)
                print(f"    {done}/{len(order)} prompts  {rate:.1f}/s", flush=True)
    missing = sum(1 for value in out if value is None)
    if missing:
        raise RuntimeError(f"{missing} prompts were not scored")
    return out


# --------------------------------------------------------------------------
def load_items(path, question_field="question", n_options=None):
    """Items and the option count they share."""
    from mcq_audit import read_rows
    rows = read_rows(Path(path))
    items, k = build_items(rows, "ideal", "distractors", "capsule_uuid", question_field,
                           n_options)
    for item, row in ((it, rows[it["row_index"]]) for it in items):
        item["question_id"] = row.get("question_id") or row.get("id") or f"row-{item['row_index']}"
    return items, k


def run_model(name, records, args, k=N_OPTIONS):
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer

    print(f"\n=== {name}", flush=True)
    tokenizer = AutoTokenizer.from_pretrained(name, padding_side="left")
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    ids, variant = letter_token_ids(tokenizer, k)
    print(f"  scoring letters as {variant.format('A')!r} "
          f"(ids {ids})", flush=True)
    try:
        model = AutoModelForCausalLM.from_pretrained(
            name, dtype=torch.bfloat16, device_map=args.device,
            attn_implementation=getattr(args, "attn", "eager"))
    except (ValueError, KeyError):
        # Some releases ship a text model inside a multimodal class (Gemma 3).
        from transformers import AutoModelForImageTextToText
        model = AutoModelForImageTextToText.from_pretrained(
            name, dtype=torch.bfloat16, device_map=args.device,
            attn_implementation=getattr(args, "attn", "eager"))
    model.eval()

    # One forward pass per distinct prompt; identical prompts across arms reuse it.
    unique, index = {}, []
    for record in records:
        text = render(tokenizer, record["prompt"])
        digest = hashlib.sha256(text.encode()).hexdigest()
        if digest not in unique:
            unique[digest] = (len(unique), text)
        index.append(unique[digest][0])
    prompts = [text for _, text in sorted(unique.values())]
    print(f"  {len(records)} conditions -> {len(prompts)} distinct prompts", flush=True)

    scored = score(model, tokenizer, prompts, ids, args.batch_size, args.device)

    rows = []
    for record, slot in zip(records, index):
        pick, probs = scored[slot]
        chosen = letters_for(k)[pick]
        rows.append({
            "model": name, "question_id": record["question_id"], "cluster": record["cluster"],
            "arm": record["arm"], "draw": record["draw"], "is_numeric": record["is_numeric"],
            "n_options": k, "repair_mode": args.repair_mode,
            # Recorded because the attribution rebuilds these conditions from the
            # question file, and a different search is a different repair.
            "search": args.search, "calibrated": bool(args.calibrate),
            "target_letter": record["target_letter"], "predicted_letter": chosen,
            "correct": int(chosen == record["target_letter"]),
            "key_rank": record["key_rank"], "released_rank": record["released_rank"],
            "redraw_applied": record["redraw_applied"],
            "chosen_rank": record["slot_ranks"][pick] if record["slot_ranks"] else None,
            "letter_probs": probs,
        })
    del model
    torch.cuda.empty_cache()
    return rows


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--jsonl", default="data/bixbench.jsonl")
    parser.add_argument("--models", nargs="+", required=True)
    parser.add_argument("--draws", type=int, default=10,
                        help="independent redraws of the distractor values per item")
    parser.add_argument("--seed", type=int, default=20260920)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--limit", type=int, default=0, help="smoke-test on the first N items")
    parser.add_argument("--out", default="results/probe_raw")
    parser.add_argument("--question-field", default="question")
    parser.add_argument("--attn", default="eager", choices=["eager", "sdpa"],
                        help="attention kernel; eager is exact and the default, sdpa is "
                             "needed for the long prompts of a 64-shot run")
    parser.add_argument("--n-options", type=int, default=None,
                        help="option count to probe (default: the file's modal count)")
    parser.add_argument("--arms", nargs="+", default=list(ARMS),
                        choices=list(ARMS) + list(EXTRA_ARMS),
                        help="which arms to run (default: the five of ARMS; "
                             "placebo_stemless is available and not run by default)")
    parser.add_argument("--repair-mode", default="rank", choices=sorted(REPAIRS),
                        help="which repair the repaired arms apply")
    parser.add_argument("--search", choices=REPAIR_SEARCHES, default="sample",
                        help="how the multi-channel repair meets its surface targets "
                             "(see mcq_audit.repair_row_multi and construct_row)")
    parser.add_argument("--calibrate", action="store_true",
                        help="draw the multi-channel repair's surface targets against "
                             "the file's own reachability rather than uniformly")
    args = parser.parse_args()

    items, k = load_items(args.jsonl, args.question_field, args.n_options)
    if args.limit:
        items = items[:args.limit]
    numeric = sum(1 for it in items if it["rank"] is not None)
    print(f"{len(items)} items with {k} options ({numeric} all-numeric), "
          f"{len({it['cluster'] for it in items})} clusters")

    records = build_conditions(items, args.draws, args.seed, k, tuple(args.arms),
                               args.repair_mode, calibrate=args.calibrate,
                               search=args.search)
    print(f"{len(records)} conditions over {len(args.arms)} arms x {args.draws} draws "
          f"({args.repair_mode} repair)")

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    for name in args.models:
        rows = run_model(name, records, args, k)
        path = out / (name.replace("/", "__") + ".jsonl.gz")
        with open_outcomes(path, "wt") as handle:
            for row in rows:
                handle.write(json.dumps(row) + "\n")
        hits = sum(r["correct"] for r in rows)
        print(f"  wrote {path}  ({hits}/{len(rows)} = {hits / len(rows):.1%} pooled)", flush=True)


if __name__ == "__main__":
    main()
