#!/usr/bin/env python3
"""Detect answer-option artifacts in multiple-choice science benchmarks.

A multiple-choice item leaks if the option set alone identifies the key. For
numeric answers the usual cause is mechanical: distractors are generated by
perturbing the true value up and down, so the key lands in the interior of the
sorted option list far more often than chance allows. A solver that never
reads the question, never sees the data, and knows no biology can then exploit
the arithmetic.

This module measures that leak, cross-validates the exploiting rule so it
cannot be accused of fitting the answer key, and provides a presentation-order
negative control. Inference is clustered on the source study wherever the
benchmark identifies one.
"""
import argparse
import ast
import json
import math
import random
import re
import statistics
from collections import Counter
from pathlib import Path

NUM_RE = re.compile(r"^[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?$")
LETTER_RE = re.compile(r"^\(([A-Z])\)\s*")
N_OPTIONS = 4


def parse_number(text):
    cleaned = str(text).strip().replace(",", "").rstrip("%").replace("−", "-")
    return float(cleaned) if NUM_RE.match(cleaned) else None


def numeric_rank(options, key_index):
    """Rank of the keyed option among the sorted numeric values, or None."""
    values = [parse_number(o) for o in options]
    if len(values) != N_OPTIONS or any(v is None for v in values) or len(set(values)) < N_OPTIONS:
        return None
    order = sorted(range(N_OPTIONS), key=lambda i: values[i])
    return order.index(key_index)


# --------------------------------------------------------------------------
# inference helpers (clustered on the source study)
# --------------------------------------------------------------------------
def cluster_bootstrap_draws(clusters, statistic, reps=10000, seed=20260918):
    """Resample whole clusters and recompute the statistic. Sorted, ascending."""
    rng = random.Random(seed)
    keys = list(clusters)
    draws = []
    for _ in range(reps):
        pooled = [x for k in (rng.choice(keys) for _ in keys) for x in clusters[k]]
        value = statistic(pooled)
        if value is not None:
            draws.append(value)
    draws.sort()
    return draws


def cluster_bootstrap(clusters, statistic, reps=10000, alpha=0.05, seed=20260918):
    draws = cluster_bootstrap_draws(clusters, statistic, reps, seed)
    if not draws:
        return (None, None)
    return (draws[int(alpha / 2 * len(draws))], draws[min(len(draws) - 1, int((1 - alpha / 2) * len(draws)))])


def normal_lower_bound(draws, alpha):
    """A one-sided lower bound at level ``alpha`` from bootstrap draws.

    Read off the draws' mean and spread rather than an order statistic. The
    level that makes the audit's rule-family tests honest is small enough that
    the matching percentile sits ten draws from the end of the resample, where
    an order statistic is mostly noise; the normal approximation is stable
    there, and whether it is *right* is settled by measurement rather than by
    assumption -- ``audit_calibration.py`` runs the whole audit on files with
    no leak in them and reports how often each test fires.
    """
    if len(draws) < 2:
        return None
    spread = statistics.pstdev(draws)
    return statistics.fmean(draws) - statistics.NormalDist().inv_cdf(1 - alpha) * spread


def rate(values):
    return statistics.fmean(values) if values else None


def chi_square_uniform(counts, n_cells=N_OPTIONS):
    """Goodness of fit against a uniform key-position distribution."""
    total = sum(counts.values())
    if not total:
        return None
    expected = total / n_cells
    stat = sum((counts.get(i, 0) - expected) ** 2 / expected for i in range(n_cells))
    return {"chi2": stat, "df": n_cells - 1, "n": total,
            "p_value_upper_bound": _chi2_sf(stat, n_cells - 1)}


def _chi2_sf(stat, df):
    """Survival function for chi-square with small integer df (no SciPy needed)."""
    if stat <= 0:
        return 1.0
    if df == 3:  # regularized upper incomplete gamma, a = 3/2
        x = stat / 2
        return math.erfc(math.sqrt(x)) + 2 * math.sqrt(x / math.pi) * math.exp(-x)
    if df == 1:
        return math.erfc(math.sqrt(stat / 2))
    if df == 2:
        return math.exp(-stat / 2)
    raise ValueError(f"unsupported df={df}")


def loco_rule_accuracy(items, reps_seed=20260918):
    """Leave-one-cluster-out accuracy of 'always pick sorted rank r'.

    The rank is selected on the other clusters only, so the reported accuracy
    is not the in-sample maximum over four candidate rules.
    """
    by_cluster = {}
    for it in items:
        by_cluster.setdefault(it["cluster"], []).append(it["rank"])
    if len(by_cluster) < 2:
        return None
    hits, n, chosen = 0, 0, Counter()
    for held_out in by_cluster:
        train = Counter(r for c, rs in by_cluster.items() if c != held_out for r in rs)
        if not train:
            continue
        best = min(range(N_OPTIONS), key=lambda r: (-train.get(r, 0), r))
        chosen[best] += 1
        for r in by_cluster[held_out]:
            hits += (r == best)
            n += 1
    return {"accuracy": hits / n if n else None, "n_scored": n,
            "rule_selected_per_fold": dict(chosen), "folds": len(by_cluster)}


# --------------------------------------------------------------------------
# per-benchmark analysis
# --------------------------------------------------------------------------
def analyse(name, items, reps=10000, chance=1 / N_OPTIONS):
    """items: dicts with 'rank' (0-3) and 'cluster'."""
    if not items:
        return None
    ranks = Counter(it["rank"] for it in items)
    interior = {}
    exterior = {}
    for it in items:
        interior.setdefault(it["cluster"], []).append(1.0 if it["rank"] in (1, 2) else 0.0)
    interior_rate = rate([x for v in interior.values() for x in v])
    lo, hi = cluster_bootstrap(interior, rate, reps=reps)
    top_rank = min(range(N_OPTIONS), key=lambda r: (-ranks.get(r, 0), r))
    best = {}
    for it in items:
        best.setdefault(it["cluster"], []).append(1.0 if it["rank"] == top_rank else 0.0)
    best_rate = rate([x for v in best.values() for x in v])
    blo, bhi = cluster_bootstrap(best, rate, reps=reps)
    return {
        "benchmark": name,
        "n_numeric_items": len(items),
        "n_clusters": len(interior),
        "rank_counts": {str(r): ranks.get(r, 0) for r in range(N_OPTIONS)},
        "rank_fractions": {str(r): ranks.get(r, 0) / len(items) for r in range(N_OPTIONS)},
        "interior_rate": interior_rate,
        "interior_rate_ci95": [lo, hi],
        "interior_rate_expected": 0.5,
        "interior_excess_significant": bool(lo is not None and lo > 0.5),
        "chi_square_vs_uniform": chi_square_uniform(ranks),
        "best_single_rank_rule": {"rank": top_rank, "accuracy": best_rate,
                                   "ci95": [blo, bhi], "chance": chance,
                                   "above_chance": bool(blo is not None and blo > chance)},
        "cross_validated_rule": loco_rule_accuracy(items),
    }


# --------------------------------------------------------------------------
# loaders
# --------------------------------------------------------------------------
def items_from_bixbench_jsonl(path):
    items, skipped = [], 0
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            if not line.strip():
                continue
            row = json.loads(line)
            distractors = row.get("distractors") or []
            if isinstance(distractors, str):
                try:
                    distractors = ast.literal_eval(distractors)
                except (ValueError, SyntaxError):
                    skipped += 1
                    continue
            options = [row["ideal"]] + list(distractors)
            if len(options) != N_OPTIONS:
                skipped += 1
                continue
            r = numeric_rank(options, 0)
            if r is None:
                skipped += 1
                continue
            items.append({"rank": r, "cluster": row["capsule_uuid"], "id": row["question_id"]})
    return items, skipped


def items_from_v10_results(path):
    """v1.0 baseline CSVs record the presented option list and the key letter."""
    import csv
    items, positions, skipped = [], Counter(), 0
    with open(path, encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle):
            try:
                choices = ast.literal_eval(row["choices"])
            except (ValueError, SyntaxError, KeyError):
                skipped += 1
                continue
            letters, texts = [], []
            for choice in choices:
                m = LETTER_RE.match(str(choice).strip())
                if not m:
                    break
                letters.append(m.group(1))
                texts.append(LETTER_RE.sub("", str(choice).strip()))
            if len(letters) != N_OPTIONS or row["target"].strip() not in letters:
                skipped += 1
                continue
            key_index = letters.index(row["target"].strip())
            positions[key_index] += 1
            r = numeric_rank(texts, key_index)
            if r is None:
                skipped += 1
                continue
            items.append({"rank": r, "cluster": row["uuid"], "id": row.get("short_qid", "")})
    return items, positions, skipped


def items_from_labbench(path, cluster_fields=("source", "sources", "paper-title", "subtask")):
    """LAB-Bench subsets ship an ideal answer plus a distractor list as JSONL."""
    items, skipped = [], 0
    with open(path, encoding="utf-8") as handle:
        for i, line in enumerate(handle):
            if not line.strip():
                continue
            row = json.loads(line)
            ideal = row.get("ideal")
            distractors = row.get("distractors") or []
            if isinstance(distractors, str):
                try:
                    distractors = ast.literal_eval(distractors)
                except (ValueError, SyntaxError):
                    skipped += 1
                    continue
            options = [ideal] + list(distractors)
            if len(options) != N_OPTIONS or ideal is None:
                skipped += 1
                continue
            r = numeric_rank(options, 0)
            if r is None:
                skipped += 1
                continue
            cluster = None
            for field in cluster_fields:
                value = row.get(field)
                if isinstance(value, list):
                    value = value[0] if value else None
                if value:
                    cluster = str(value)
                    break
            items.append({"rank": r, "cluster": cluster or f"item-{i}", "id": str(row.get("id", i))})
    return items, skipped


def matched_subset_comparison(jsonl, zero_shot_dir, reps=10000):
    """Score the published no-data runs on exactly the items the rule scores.

    The model-free rule only applies to items whose four options parse as
    distinct numbers. Comparing its accuracy against a model's accuracy over
    the full question set would be comparing different populations, so this
    restricts both sides to the same items.
    """
    import csv

    rows, numeric = {}, {}
    with open(jsonl, encoding="utf-8") as handle:
        for line in handle:
            if not line.strip():
                continue
            row = json.loads(line)
            qid = row["question_id"].lower()
            rows[qid] = row
            distractors = row.get("distractors") or []
            if isinstance(distractors, str):
                try:
                    distractors = ast.literal_eval(distractors)
                except (ValueError, SyntaxError):
                    distractors = []
            options = [row.get("ideal")] + list(distractors)
            if len(options) == N_OPTIONS:
                rank = numeric_rank(options, 0)
                if rank is not None:
                    numeric[qid] = {"rank": rank, "cluster": row["capsule_uuid"]}

    out = {"n_matched_items": len(numeric), "runs": {}}
    for path in sorted(Path(zero_shot_dir).glob("*.csv")):
        clusters = {}
        with path.open(encoding="utf-8", newline="") as handle:
            for row in csv.DictReader(handle):
                qid = (row.get("uuid") or "").strip().lower()
                if qid in numeric:
                    clusters.setdefault(numeric[qid]["cluster"], []).append(
                        1.0 if str(row.get("correct", "")).strip().lower() == "true" else 0.0)
        flat = [x for g in clusters.values() for x in g]
        if not flat:
            continue
        lo, hi = cluster_bootstrap(clusters, rate, reps=reps)
        out["runs"][path.stem] = {"accuracy": rate(flat), "n": len(flat), "ci95": [lo, hi]}
    return out


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--jsonl", type=Path, default=Path("data/bixbench.jsonl"))
    parser.add_argument("--v10-results", type=Path,
                        default=Path("data/external/zero_shot_v10/"
                                     "bixbench_llm_baseline_refusal_False_mcq_gpt-4o_1.0.csv"))
    parser.add_argument("--labbench-dir", type=Path, default=Path("data/external/labbench"))
    parser.add_argument("--reps", type=int, default=10000)
    parser.add_argument("--output", type=Path, default=Path("results/option_artifacts.json"))
    args = parser.parse_args()

    report = {"n_options": N_OPTIONS, "chance": 1 / N_OPTIONS,
              "bootstrap_reps": args.reps, "benchmarks": []}

    items, skipped = items_from_bixbench_jsonl(args.jsonl)
    v15 = analyse("BixBench v1.5", items, reps=args.reps)
    v15["non_numeric_or_unparsed_items"] = skipped
    report["benchmarks"].append(v15)

    if args.v10_results.exists():
        items10, positions, skipped10 = items_from_v10_results(args.v10_results)
        v10 = analyse("BixBench v1.0", items10, reps=args.reps)
        v10["non_numeric_or_unparsed_items"] = skipped10
        v10["presentation_order_control"] = {
            "description": "Letter position of the key as actually presented to the solver.",
            "counts": {str(k): v for k, v in sorted(positions.items())},
            "chi_square_vs_uniform": chi_square_uniform(positions),
        }
        report["benchmarks"].append(v10)

    if args.labbench_dir.exists():
        for parquet in sorted(args.labbench_dir.glob("*.jsonl")):
            lb_items, lb_skipped = items_from_labbench(parquet)
            record = analyse(f"LAB-Bench {parquet.stem}", lb_items, reps=args.reps)
            if record:
                record["non_numeric_or_unparsed_items"] = lb_skipped
                report["benchmarks"].append(record)

    zs_dir = Path("data/external/zero_shot_v15")
    if args.jsonl.exists() and zs_dir.exists():
        report["matched_subset_comparison"] = matched_subset_comparison(
            args.jsonl, zs_dir, reps=args.reps)

    for rec in report["benchmarks"]:
        cv = rec.get("cross_validated_rule") or {}
        print(f"\n{rec['benchmark']}: {rec['n_numeric_items']} numeric items "
              f"in {rec['n_clusters']} clusters")
        print("  key rank among sorted options: " +
              "  ".join(f"r{r}={rec['rank_fractions'][str(r)]:.1%}" for r in range(N_OPTIONS)))
        print(f"  interior rate {rec['interior_rate']:.1%} "
              f"[{rec['interior_rate_ci95'][0]:.1%}, {rec['interior_rate_ci95'][1]:.1%}] "
              f"vs 50% expected"
              f"{'  <-- excess' if rec['interior_excess_significant'] else ''}")
        b = rec["best_single_rank_rule"]
        print(f"  model-free rule 'pick rank {b['rank']}': {b['accuracy']:.1%} "
              f"[{b['ci95'][0]:.1%}, {b['ci95'][1]:.1%}] vs {b['chance']:.0%} chance")
        if cv.get("accuracy") is not None:
            print(f"  leave-one-cluster-out cross-validated: {cv['accuracy']:.1%} "
                  f"(n={cv['n_scored']}, folds={cv['folds']})")
        if "presentation_order_control" in rec:
            ctl = rec["presentation_order_control"]["chi_square_vs_uniform"]
            print(f"  control - presented letter position: chi2={ctl['chi2']:.2f}, "
                  f"p~{ctl['p_value_upper_bound']:.3f} (uniform shuffling expected)")

    matched = report.get("matched_subset_comparison")
    if matched:
        print(f"\nOn the same {matched['n_matched_items']} numeric items, no data:")
        for name, rec in sorted(matched["runs"].items(), key=lambda kv: -kv[1]["accuracy"]):
            if "mcq-refusal-False" in name:
                print(f"  {name:52s} {rec['accuracy']:.1%} "
                      f"[{rec['ci95'][0]:.1%}, {rec['ci95'][1]:.1%}]")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(f"\nwrote {args.output}")


if __name__ == "__main__":
    main()
